### ISSUE TITLE
Correlation coefficient labels for non-significant correlations

### ISSUE THREAD

**Issue by axitamm** [kassambara/ggcorrplot#17]
Thank you for developing this package. It is excellent. I have one minor issue:

When using lab = TRUE and insig = "blank" together in the ggcorrplot function, the figure results in zeros being placed in all the "blank" squares. Is there a way to avoid zeroes or any labels from being placed in "blank" (non-significant) squares?

Thank you,

**Comment by kassambara** [comment]
fixed now, thanks
