### ISSUE TITLE
appropriate use for data in which correlations already calculated

### ISSUE THREAD

**Issue by devonorourke** [kassambara/ggcorrplot#20]
Good morning,
In the example documentation, the initial dataset is converted into a correlation matrix with a single `cor_pmat` function. In my case, I have a data.frame object in which the correlation value for each pairwise comparison is already computed:

```
Item1    Item2    correlation
A          B       0.05
A          C       0.25
A          D       0.33
B          C       0.88
B          D       0.72
C          D       0.12
```

I've tried converting to generate a matrix with `dcast(df, Item1~Item2, value.var="correlation")`, but it's not a symmetric one (in part because I never compared Item1 to itself).

Is there any way in which your package will accept a data.frame object like this where no further values need to be computed?

Thanks for your consideration

**Comment by kassambara** [comment]
Hi, only a matrix is supported in wide format
