### ISSUE TITLE
labs function not working for X and Y

### ISSUE THREAD

**Issue by Ajfrick** [kassambara/ggcorrplot#21]
Hi, I'm having trouble adding a label to the x and y axes using the labs function in ggplot. Title, subtitle, and caption are working fine, but I'd like to labels across horizontal and vertical axis. 

my code looks like 
p = ggcorrplot(<cormat>) + 
      theme(<options>) + 
      geom_abline() + 
      labs( x = "X", y = "Y", title = "Title", subtitle = "subtitle", caption = "caption")

Everything works as intended except for the X and Y labels.

I didn't see an argument within the ggcorrplot function for modifying these. Is this functionality currently supported somehow?

Thank you,

**Comment by kassambara** [comment]
Hi,

By default we blank axis titles. You can revert back this as follow:

```r
p + 
  theme(
    axis.title.x = element_text(),
    axis.title.y = element_text(angle = 90)
    ) +
  labs(x = "x axis", y = "y axis")
```
