### ISSUE TITLE
`hc.method` argument has no effect

### ISSUE THREAD

**Issue by mitchelfruin** [kassambara/ggcorrplot#29]
Firstly, thanks very much. This package is super useful for the
exploratory data analysis that I’m required to do for work. In
particular, the `hc.order` argument makes the final graph very visualy
appealing and easy to interpret.

I was playing around with the `hc.method` argument today and realised
that choosing a different linkage criterion was not having an effect on
the order of the variables in the final visualisation.

Here’s a representative example:

    # Fake data
    set.seed(1)
    master <- tibble::tibble(var_1 = rnorm(100),
                             var_2 = 1*var_1  + rnorm(100), # positive corr
                             var_3 = rnorm(100),
                             var_4 = rnorm(100),
                             var_5 = rnorm(100),
                             var_6 = rnorm(100),
                             var_7 = rnorm(100),
                             var_8 = -1*var_4 + rnorm(100)) # negative corr

    # Get correlations
    pearson <- stats::cor(master, method = "pearson")

Compare the different linkage methods:

    # Corrplot ordered by hierarchical clustering with different linkage criteria
    ggcorrplot::ggcorrplot(pearson, hc.order = T, hc.method = "complete")

![image](https://user-images.githubusercontent.com/53878447/80401838-e96dcf00-88b4-11ea-8c39-7a01dea5f1e4.png)

    ggcorrplot::ggcorrplot(pearson, hc.order = T, hc.method = "single")

![image](https://user-images.githubusercontent.com/53878447/80401870-f38fcd80-88b4-11ea-9011-a63666dae675.png)

    ggcorrplot::ggcorrplot(pearson, hc.order = T, hc.method = "average")

![image](https://user-images.githubusercontent.com/53878447/80401907-ff7b8f80-88b4-11ea-83df-7864233077da.png)

The `hc.method` argument is having no effect.

So, I did the clustering manually to check if the order should be
changing.

    # Do hierarchical clustering manually as the function does

    # First, it rounds the correlations to 2 digits by default
    rounded <- round(pearson, 2)
    # Then it calculates distance
    dist <- as.dist((1 - rounded)/2)
    # Then it runs clustering with specified method
    complete_hclust <- hclust(dist, method = "complete")
    complete_hclust$order

    ## [1] 7 8 5 1 2 6 3 4

    single_hclust <- hclust(dist, method = "single")
    single_hclust$order

    ## [1] 6 5 1 2 7 8 3 4

    average_hclust <- hclust(dist, method = "average")
    average_hclust$order

    ## [1] 3 4 6 5 1 2 7 8

We can see that the order should be changing.

I have submitted a pull request with a suggested fix for this issue. 

Thanks again for developing the package.

**Comment by kassambara** [comment]
fixed now, thank you
