### ISSUE TITLE
cor_pmat gives totally wrong p-values

### ISSUE THREAD

**Issue by maexwellsch** [kassambara/ggcorrplot#3]
When I use cor_pmat, the values are totally wrong (or other than) using rcorr() from Hmisc or even cor.test()

How can this be? What Method does cor_pmat use? Can one define it?

**Comment by kassambara** [comment]
Hi @maexwellsch,

cor_pmat() gives the same result as cor.test and Hmisc::rcorr(). 

Please find below a reproducible example:

- Compute p-values using ggcorrplot

```r
library(ggcorrplot)
p.mat <- cor_pmat(as.matrix(mtcars[, 1:5]))
p.mat
```

```
              mpg          cyl         disp           hp         drat
mpg  0.000000e+00 6.112687e-10 9.380327e-10 1.787835e-07 1.776240e-05
cyl  6.112687e-10 0.000000e+00 1.802838e-12 3.477861e-09 8.244636e-06
disp 9.380327e-10 1.802838e-12 0.000000e+00 7.142679e-08 5.282022e-06
hp   1.787835e-07 3.477861e-09 7.142679e-08 0.000000e+00 9.988772e-03
drat 1.776240e-05 8.244636e-06 5.282022e-06 9.988772e-03 0.000000e+00
```


- Compute p-values using Hmisc

```r
 library(Hmisc)
res.hmisc <- rcorr(as.matrix(mtcars[,1:5]))
res.hmisc$P
```

```
              mpg          cyl         disp           hp         drat
mpg            NA 6.112697e-10 9.380354e-10 1.787838e-07 1.776241e-05
cyl  6.112697e-10           NA 1.803002e-12 3.477856e-09 8.244635e-06
disp 9.380354e-10 1.803002e-12           NA 7.142686e-08 5.282028e-06
hp   1.787838e-07 3.477856e-09 7.142686e-08           NA 9.988768e-03
drat 1.776241e-05 8.244635e-06 5.282028e-06 9.988768e-03           NA
```

Best,

A.

**Comment by maexwellsch** [comment]
Hi,

Thank you so much for your fast reply! I am sorry, to accuse you of your
error!

I did a bad mistake and used the wrong data to create the p-values... I am
so sorry... Everything works fine now!

Just one thing: Can you tell me what method cor_pmat() uses? (Pearson,
Spearman, etc.)

Thank you very much,
Best
Max

2016-07-18 10:30 GMT+02:00 Alboukadel KASSAMBARA <notifications@github.com>:

**Comment by kassambara** [comment]
The function cor_pmat() uses the standard function cor.test(), in the back-end, to compute correlation test. So the default method is "pearson". Note also that, cor_pmat() accepts any other arguments accepted by the function cor.test().

Have a great day!
A.
