### ISSUE TITLE
Warning messages on cor_pmat()?

### ISSUE THREAD

**Issue by jfrojas60** [kassambara/ggcorrplot#7]
Hi,

I was trying to use the cor_pmat() function but for Spearman (the default is Pearson), so i typed:
**cor_pmat(mtcars, method="spearman")** ,  as a result i got a p-value matrix which is the same as for other functions (e.g. rcorr in Hmisc). But am also getting this message **"There were 50 or more warnings (use warnings() to see the first 50)"**. I don't see any problems in the results so i don't know why the messages!
Will i have any issues by doing "p.mat <- cor_pmat(mtcars)"? Or running the "ggcorrplot" later?

Thanks!

**Comment by kassambara** [comment]
Hi,

Don't worry about these warnings. As spearman method is rank-based, it will always generate a warning if there are ties in the data. The warnings inform you that it's not possible to compute the exact p-value when there are ties.

You'll have the same warning using the R base function

```r
cor.test(mtcars$mpg, mtcars$cyl, method = "spearman")
```

so, just ignore these warnings.

**Comment by jfrojas60** [comment]
Hi,

Thanks for the fast response! Am a beginner in R so please excuse my questions if they are dumb!  I was trying to run your script but for spearman. And also want to change the sig.level for the rejection criteria in the graphics, the default is 0.01 right?
By the way, if i use your script, how should i properly quote it or make reference to it?

Thanks!

**Comment by kassambara** [comment]
The default rejection level is 0.05, but you  can change this by specifying the argument `sig.level`. See the documentation of `ggcorrplot`(), argument sig.level.

To cite `ggcorrplot` in a publication, use the output returned by the following R command:

```r
citation("ggcorrplot")
````

For example:

 Alboukadel Kassambara (2016). ggcorrplot: Visualization of a Correlation Matrix using
  'ggplot2'. R package version 0.1.1. http://www.sthda.com/english/wiki/ggcorrplot

**Comment by jfrojas60** [comment]
Yea, i figured it out after i made the comment! I have been playing with your script options. Is there a way to put in "bold" only the significant coefficients numbers and leave the rest normal?

I will do the citing!

thanks!

**Comment by kassambara** [comment]
I will work on that, thanks!

**Comment by jfrojas60** [comment]
Thank you very much!
