### ISSUE TITLE
Scaling colors according to the actual range of values

### ISSUE THREAD

**Issue by gufranca** [kassambara/ggcorrplot#9]
Hello!
I am using the amazing ggcorrplot to plot the heatmap of my correlation matrix. However, I am having an issue with the color representation. Since the range of values in my data goes from 0.8 to 1 (instead of -1 to 1), all the colors/correlations look red because the legend goes from -1(blue) to 1(red). So it is difficult to visually distinguish the differences (see fig attached). Is there any way to scale the colors based on the range of the actual values?

![test](https://user-images.githubusercontent.com/1247681/36222378-18b1e28c-118f-11e8-871d-49b085a68798.png)

I appreciate any help on this!
Gustavo

**Comment by clairemcwhite** [comment]
You can rescale the fill colors by doing:

`p <- ggcorrplot(....)
p + scale_fill_gradient2(limit = c(0.8,1), low = "blue", high =  "red", mid = "white", midpoint = 0.9)`

**Comment by gufranca** [comment]
Thanks for that!
